### ISSUE TITLE
Boats not having, border like player,

### ISSUE THREAD

**Issue by Zhado8** [cheyao/minecraft-plugin#2]
![image](https://github.com/user-attachments/assets/80005623-c89c-4a16-8533-15d1adeae169)

Boating off the world gave me a heart attack Xd

**Comment by cheyao** [comment]
Oppsie, that's entirely my fault, forgot that you can get on boats to cross the boarder lol.

I'm going to fix it tonight or tomorrow!

Thanks for the bug report!

**Comment by cheyao** [comment]
Sorry for the delay, i've been a bit busy with studies.

This should be fixed with [this new commit](https://github.com/cheyao/minecraft-plugin/commit/4b8c8f615f5d742f662ec393caa870179d56fbd4#diff-3d103fc7c312a3e136f88e81cef592424b8af2464c468116545c4d22d6edcf19R7)

I'll push it on Modrinth as soon as I fix the github actions!

**Comment by cheyao** [comment]
Here :D https://modrinth.com/mod/2d-minecraft/version/ZuMRxMkL
